---
title: "Data Science Plotly Visuals"
output:
      html_document
---

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data("instacart")

insta_data = instacart %>%
  filter(department == "beverages") %>%
  mutate(reordered = recode(reordered, "1" = "Yes", "0" = "No"), 
         order_dow = recode(order_dow, "0" = "Sunday", "1" = "Monday", "2" = "Tuesday", 
                             "3" = "Wednesday", "4" = "Thursday", "5" = "Friday", "6" = "Saturday")) %>%
  select (aisle, product_name, order_hour_of_day, order_dow, reordered) 

```

```{r}
count = insta_data %>% 
  group_by(aisle) %>%
  summarize(reordered = n())
count

```

### Bar Chart 
* Number of times goods from each aisle were reorderd within the beverage department. 
```{r - bar chart}
count %>%
  plot_ly(x = ~aisle, y = ~reordered, color = ~aisle, type = "bar", text = ~aisle) %>%
  layout(xaxis = list(title = "Aisle Category"),
         yaxis = list(title = "Total items reordered"))

```

### Boxplot
* Distribution of each aisle being purchased across all hours of day.  
```{r - boxplot}
insta_data %>%
  plot_ly(x = ~aisle, y = ~order_hour_of_day, color = ~aisle, type = "box") %>%
layout(xaxis = list(title = "Aisle Category"),
         yaxis = list(title = "Hour of Day Ordered"))

```

### Line plot
* Number of times goods from each aisle were reorderd within the beverage department. 